### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-cterrasid#1]
Good job @cterrasid  !!!

Here you have some tips to finish the game:

- [x] Define the logic to generate and save the random number (remember we gave you a sample code). Since the function is not anonymous you don't need to store it into a constant. Instead, execute it, and store in a constant the returned value.
- [x] Remember to convert input value to number
- [x] Finish the feedback logic
- [x] Define the logic to make the counter work
- [x] Define a good structure of folders and files for the project
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute to show a field's hint

Let me know if you have any doubts ;)

Go for it!!

**Comment by cterrasid** [comment]
I just can't understand the logic of the counter... I saw it in the exercise solution but I don't want to copy it without undertanding it...

Panic mode : ON :sob:

**Comment by cterrasid** [comment]
I've solved the problem with the counter!!!!  :grinning:

**Comment by nasivuela** [comment]
I do not see any changes :S Maybe you forget to push, or merge to master?

**Comment by cterrasid** [comment]
I've forgot to merge with master but It's solved... I just need to create the styles of the project...

**Comment by nasivuela** [comment]
Well done @cterrasid !

Let's keep improving it:

- [ ] Move the feedback logic to a function an execute it on each click
- [ ] Move you counter logic into a function and execute it on each click
- [ ] You are writing many times "feedbackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'feedbackEl'?
- [ ] Clean it a little removing comments and logs

Then you can improve the game as you please, here you have some ideas:
- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Go for it!

**Comment by nasivuela** [comment]
Cool!

![](https://media.giphy.com/media/K0usvg1aP657W/giphy.gif)
